### ISSUE TITLE
ShulkerServerAgent dont work on 1.18.2

### ISSUE THREAD

**Issue by Svetch** [jeremylvln/Shulker#274]
### What happened?

Our server network is uses Purpur 1.18.2 but on server startup the ShulkerServerAgent is crashing.
We want to migrate our full network(around 50 servers) to Shulker so it is important to us to be work with minecraft version 1.18.2.

### What components are involved in your issue?

Server Agent (Paper)

### Version

0.4.0

### Kubernetes Version

1.28

### Relevant log output

```Shell
[13:08:44 ERROR]: Error occurred while enabling ShulkerServerAgent v0.4.0 (Is it up to date?)                                                                                                                 
java.lang.NoSuchMethodError: 'io.papermc.paper.threadedregions.scheduler.AsyncScheduler org.bukkit.Server.getAsyncScheduler()'                                                                                
    at io.shulkermc.serveragent.paper.ServerInterfacePaper.scheduleRepeatingTask(ServerInterfacePaper.kt:46) ~[shulker-server-agent-0.4.0-paper.jar:?]                                                        
    at io.shulkermc.serveragent.tasks.HealthcheckTask.schedule(HealthcheckTask.kt:13) ~[shulker-server-agent-0.4.0-paper.jar:?]                                                                               
    at io.shulkermc.serveragent.ShulkerServerAgentCommon.onServerInitialization(ShulkerServerAgentCommon.kt:41) ~[shulker-server-agent-0.4.0-paper.jar:?]                                                     
    at io.shulkermc.serveragent.paper.ShulkerServerAgentPaper.onEnable(ShulkerServerAgentPaper.kt:11) ~[shulker-server-agent-0.4.0-paper.jar:?]                                                               
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]                                                                                                
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]                                                                                  
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]                                                                                 
    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-81]                                                                                          
    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-81]                                                                                         
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634) ~[paper-1.19.jar:git-Paper-81]                                                                                               
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:420) ~[paper-1.19.jar:git-Paper-81]                                                                                                
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-81]                                                                                     
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1122) ~[paper-1.19.jar:git-Paper-81]                                                                                               
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]                                                                                            
    at java.lang.Thread.run(Unknown Source) ~[?:?]                                                                                                                                                            
[13:08:44 INFO]: [ShulkerServerAgent] Disabling ShulkerServerAgent v0.4.0                                                                                                                                     
[13:08:44 ERROR]: Error occurred while disabling ShulkerServerAgent v0.4.0 (Is it up to date?)                                                                                                                
kotlin.UninitializedPropertyAccessException: lateinit property healthcheckTask has not been initialized                                                                                                       
    at io.shulkermc.serveragent.ShulkerServerAgentCommon.onServerShutdown(ShulkerServerAgentCommon.kt:60) ~[shulker-server-agent-0.4.0-paper.jar:?]                                                           
    at io.shulkermc.serveragent.paper.ShulkerServerAgentPaper.onDisable(ShulkerServerAgentPaper.kt:15) ~[shulker-server-agent-0.4.0-paper.jar:?]                                                              
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]                                                                                                
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]                                                                                 
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]                                                                                
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]                                                                                  
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]                                                                                 
    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-81]                                                                                          
    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-81]                                                                                         
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634) ~[paper-1.19.jar:git-Paper-81]                                                                                               
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:420) ~[paper-1.19.jar:git-Paper-81]                                                                                                
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-81]                                                                                     
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1122) ~[paper-1.19.jar:git-Paper-81]                                                                                               
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]                                                                                            
    at java.lang.Thread.run(Unknown Source) ~[?:?]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
